export const LANGUAGES = [
  ["en", "English"],
  ["fr", "Français"],
  ["es", "Español"],
  ["pt", "Português"],
  ["de", "Deutsch"],
  ["zh", "简体中文"],
  ["hi", "हिन्दी"],
  ["bn", "বাংলা"],
  ["ur", "اردو"],
  ["id", "Bahasa Indonesia"],
  ["ar", "العربية"],
  ["ru", "Русский"],
  ["ja", "日本語"],
] as const;

export type LangCode = typeof LANGUAGES[number][0];

type Dict = Record<string, string>;

const en: Dict = {
  commandNeedsAttention: "Mining command: attention required", dismissError: "Dismiss",
  savingBeforeStart: "Saving changed settings before starting…", commandInProgress: "Command in progress",
  commandTimeout: "No reply received in time. The command may still have been processed. Check the profile state and backend.log before retrying.",
  bulkStartFailed: "Some profiles could not start", bulkStartSucceeded: "profile(s) acknowledged",
  noEnabledProfiles: "No enabled mining profile to start.", configUnavailable: "Configuration has not loaded yet.",
  schedulerPaused: "schedule paused manually", schedulerPausedHelp: "Stopped for the current schedule occurrence. Start resumes it immediately. Later occurrences run normally.",
  dashboard: "Dashboard", miners: "Miners", schedules: "Schedules", console: "Console", settings: "Settings",
  dashboardTitle: "Multi-miner dashboard", minersTitle: "Miners & profiles", schedulesTitle: "Mining schedules", settingsTitle: "Settings",
  desktopMode: "Desktop mode · orchestrator active", headlessMode: "Headless mode · web interface", connecting: "Connecting to MinerDesk…",
  unsaved: "unsaved changes", save: "Save", startAll: "Start all", stopAll: "Stop all", start: "Start", stop: "Stop", restart: "Restart", config: "Config",
  activeMiners: "Active miners", totalPower: "Total power", maxTemp: "Max temp", sharesAR: "Shares A / R",
  filterPlaceholder: "Filter name, algorithm, pool, GPU…", allMiners: "All miners", allStates: "All states", running: "Running", stopped: "Stopped", disabled: "Disabled", minerDisabledHint: "This profile is disabled. Enable it in Config before starting mining.",
  profile: "Profile", engine: "Engine", algoGpu: "Algo / GPU", state: "State", hashrate: "Hashrate", uptime: "Uptime", mining: "MINING", scheduled: "scheduled",
  profiles: "Profiles", profilesHelp: "Each profile can run a different miner and one or more GPUs.", add: "Add", duplicate: "Duplicate", remove: "Delete",
  newMiner: "New miner", profileConfigHelp: "Generic configuration automatically adapted to the selected mining engine.",
  name: "Name", executable: "Executable", browse: "Browse", downloadGithub: "Download from GitHub", enabled: "Enabled", algorithm: "Algorithm", pool: "Pool",
  wallet: "Wallet / username", secondaryWallet: "Secondary wallet", mergeSeparator: "Merge separator", mergeSecondary: "Concatenate the secondary wallet (for example PRL+NOCK)", poolPassword: "Pool password", worker: "Worker",
  gpuTuning: "GPU & tuning", gpuUse: "GPUs to use", gpuUseHelp: "MinerDesk automatically adapts GPU selection and tuning syntax to the selected miner.", refresh: "Refresh", detecting: "Detecting…",
  allGpus: "All GPUs", allGpusHelp: "Let the miner automatically use all compatible GPUs", noGpu: "No detailed GPU was detected. You can use manual IDs below.",
  manualIds: "Manual IDs / diagnostics", savedGpuIds: "Saved GPU IDs", source: "Source", perGpuTuning: "Per-GPU tuning", perGpuHelp: "Core clock, power limit and fan can be set independently for every selected GPU. Blank values are left unchanged.",
  coreClock: "Core clock MHz", powerLimit: "Power limit W", fan: "Fan %", inherit: "Default / unchanged", minerApiPort: "Miner API port", disableCpu: "Disable CPU mining",
  gpuOverlap: "Allow the same GPU to be shared with another process (advanced / dual mining)", advancedArgs: "Advanced arguments", advancedPlaceholder: "Miner-specific arguments not covered by MinerDesk",
  scheduler: "Scheduler", schedulerHelp: "The scheduler runs in the backend even when no web window is open.", addWindow: "Add window", noSchedule: "No schedule configured.", scheduleName: "Mining window", active: "Enabled", delete: "Delete", startTime: "Start", endTime: "End", profilesAffected: "Profiles", crossesMidnight: "Windows crossing midnight are handled automatically (for example 22:00 → 07:00).",
  lines: "lines", webTitle: "Web interface & headless", webHelp: "The desktop app always runs a local web/API server. It can optionally be exposed to your LAN.", currentMode: "Current mode", minerCrashGuard: "Miner crash guard", minerCrashGuardActive: "Active · Windows Job Object", minerCrashGuardUnavailable: "Unavailable / not applicable", localUrl: "Local web URL", configFile: "Configuration", webPort: "Web port", lanAccess: "Allow LAN access", lanAccessHelp: "Bind the desktop web server to 0.0.0.0 so other devices on your LAN can open MinerDesk.", accessToken: "Remote access token", generateToken: "Generate token", restartRequired: "Changing the web port or LAN binding requires restarting MinerDesk.", lanUrl: "LAN URL example",
  language: "Language", languageHelp: "English is the default. Language choice is shared by desktop and web UI.",
  windowsBehavior: "Windows behavior", windowsBehaviorHelp: "Choose how MinerDesk integrates with your Windows session. Both options are disabled by default.", startWithWindows: "Start MinerDesk with Windows", startWithWindowsHelp: "Launch the MinerDesk desktop application automatically when you sign in to Windows.", closeToTray: "Minimize to the notification area when closing", closeToTrayHelp: "The close button hides MinerDesk instead of quitting it. Use the tray icon to reopen it; Quit fully exits MinerDesk and stops the headless backend.", windowsBehaviorSaveHint: "Save the configuration to apply these Windows integration options.", windowsIntegrationError: "Windows integration error",
  desktopLifecycle: "Desktop lifecycle", desktopLifecycleHelp: "The privileged backend now follows the Desktop process lifetime.", stopBackendOnExit: "Backend stops automatically with MinerDesk Desktop", stopBackendOnExitWarning: "Close-to-tray keeps MinerDesk and the backend running; a real quit stops miners and the headless backend.",
  windowsSecurity: "Windows security", windowsSecurityHelp: "Rules apply only to MinerDesk-managed miner executables.", firewall: "Outbound firewall", firewallHelp: "Per-executable outbound rules for downloaded miners.", defender: "Microsoft Defender exclusion", defenderHelp: "Excludes only the managed miner folder.", enabledState: "Enabled", enable: "Enable", folder: "Folder",
  supportedEngines: "Supported engines", supportedHelp: "Automatic GitHub download or custom executable.", manualPath: "Manual path",
  saveOk: "Configuration saved", commandSent: "Command sent", download: "Download", gpuDetection: "GPU detection", keepGpu: "At least one GPU must remain selected. Choose “All GPUs” to return to automatic mode.", confirmDelete: "Delete this miner profile?",
  webTokenSession: "Web token for this session", emptyLocal: "Empty for desktop/local access", tokenRemoteHint: "Remote clients must use ?token=... or the X-MinerDesk-Token header.",
  afterMining: "After mining", doNothing: "Do nothing", sleepPc: "Sleep", hibernatePc: "Hibernate", countdownSeconds: "Countdown (seconds)", requirePowerConfirmation: "Require an open Desktop/Web confirmation window", wakeBeforeStart: "Wake computer before start", wakeMinutesBefore: "Wake minutes before", wakeWindowsNote: "Scheduled wake timers are currently created automatically on Windows; hardware/power-plan support is required.",
  sleepCountdownTitle: "Computer sleep scheduled", hibernateCountdownTitle: "Computer hibernation scheduled", scheduleEnded: "Mining schedule “{name}” has ended.", closeCancelsSleep: "The computer will perform the selected power action when the countdown reaches zero. Closing or cancelling this window prevents it.", sleepNow: "Sleep now", hibernateNow: "Hibernate now", cancel: "Cancel",
  privilegedBackend: "Privileged backend", backendOnline: "Backend online", backendOffline: "Backend offline", backendConnected: "Connected", startBackend: "Start backend", startingBackend: "Starting…", restartBackend: "Restart backend", repairBackend: "Repair backend", backendDiagnostics: "Backend diagnostics", taskInstalled: "task installed", taskMissing: "task missing", backendChecking: "checking…", portUsedBy: "port used by", taskState: "Scheduled task", lastTaskResult: "Last task result", backendExecutable: "Backend executable", listener: "Port listener", backendActionFailed: "Backend action failed",
  devTipKicker: "VOLUNTARY SUPPORT", devTipTitle: "Support MinerDesk development", devTipHelp: "Optional and 0% by default. If you choose a tip, MinerDesk occasionally mines for the developer for that share of time, then automatically returns to your wallet. Change or disable it anytime.", devTipPercent: "Dev tip", devTipDetected: "Payout network detected", devTipUnsupported: "Network not recognized yet — dev tip will not run for this profile.", devTipOff: "No tip — MinerDesk remains fully available.", devTipThanksSmall: "A little spark helps ✦", devTipThanks: "Thank you for supporting development ♥", devTipThanksBig: "Amazing support — thank you! ✨", devTipActive: "DEV TIP",
};

const fr: Dict = {
  commandNeedsAttention: "Commande de minage : vérification nécessaire", dismissError: "Fermer",
  savingBeforeStart: "Enregistrement des modifications avant le démarrage…", commandInProgress: "Commande en cours",
  commandTimeout: "Aucune réponse dans le délai prévu. La commande a peut-être été traitée. Vérifie l’état du profil et backend.log avant de réessayer.",
  bulkStartFailed: "Certains profils n’ont pas pu démarrer", bulkStartSucceeded: "profil(s) pris en compte",
  noEnabledProfiles: "Aucun profil de minage activé à démarrer.", configUnavailable: "La configuration n’est pas encore chargée.",
  schedulerPaused: "planification suspendue manuellement", schedulerPausedHelp: "Arrêté pour le créneau en cours. Démarrer le relance immédiatement. Les créneaux suivants restent actifs.",
  dashboard:"Dashboard", miners:"Mineurs", schedules:"Horaires", console:"Console", settings:"Paramètres", dashboardTitle:"Dashboard multi-miners", minersTitle:"Mineurs & profils", schedulesTitle:"Plages horaires", settingsTitle:"Paramètres",windowsBehavior:"Comportement Windows",windowsBehaviorHelp:"Choisissez comment MinerDesk s’intègre à votre session Windows. Les deux options sont désactivées par défaut.",startWithWindows:"Démarrer MinerDesk avec Windows",startWithWindowsHelp:"Lance automatiquement l’application MinerDesk à l’ouverture de votre session Windows.",closeToTray:"Réduire dans la zone de notification à la fermeture",closeToTrayHelp:"Le bouton Fermer masque MinerDesk au lieu de quitter l’application. Utilisez l’icône de la zone de notification pour le rouvrir ; Quitter ferme complètement MinerDesk et arrête le backend headless.",windowsBehaviorSaveHint:"Enregistrez la configuration pour appliquer ces options Windows.",windowsIntegrationError:"Erreur d’intégration Windows",desktopLifecycle:"Cycle de vie Desktop",desktopLifecycleHelp:"Le backend privilégié suit maintenant le cycle de vie du processus Desktop.",stopBackendOnExit:"Le backend s’arrête automatiquement avec MinerDesk Desktop",stopBackendOnExitWarning:"La réduction dans la zone de notification garde MinerDesk et le backend actifs ; une vraie fermeture arrête les mineurs et le backend headless.",
  desktopMode:"Mode desktop · orchestrateur actif", headlessMode:"Mode headless · interface web", connecting:"Connexion à MinerDesk…", unsaved:"modifications non enregistrées", save:"Enregistrer", startAll:"Tout démarrer", stopAll:"Tout arrêter", start:"Démarrer", stop:"Arrêter", restart:"Redémarrer", config:"Config",
  activeMiners:"Mineurs actifs", totalPower:"Puissance totale", maxTemp:"Temp. max", sharesAR:"Shares A / R", filterPlaceholder:"Filtrer nom, algo, pool, GPU…", allMiners:"Tous les mineurs", allStates:"Tous les états", running:"En cours", stopped:"Arrêtés", disabled:"Désactivé", minerDisabledHint:"Ce profil est désactivé. Activez-le dans Config avant de lancer le minage.",
  profile:"Profil", engine:"Moteur", algoGpu:"Algo / GPU", state:"État", hashrate:"Hashrate", uptime:"Uptime", mining:"MINING", scheduled:"planifié", profiles:"Profils", profilesHelp:"Chaque profil peut exécuter un outil différent et un ou plusieurs GPU.", add:"Ajouter", duplicate:"Dupliquer", remove:"Supprimer", newMiner:"Nouveau mineur", profileConfigHelp:"Configuration générique adaptée automatiquement au moteur choisi.",
  name:"Nom", executable:"Exécutable", browse:"Parcourir", downloadGithub:"Télécharger depuis GitHub", enabled:"Activé", algorithm:"Algorithme", pool:"Pool", wallet:"Wallet / username", secondaryWallet:"Wallet secondaire", mergeSeparator:"Séparateur merge", mergeSecondary:"Concaténer le wallet secondaire (ex. PRL+NOCK)", poolPassword:"Mot de passe pool", worker:"Worker",
  gpuTuning:"GPU & réglages", gpuUse:"GPU à utiliser", gpuUseHelp:"MinerDesk adapte automatiquement la sélection et les réglages au mineur choisi.", refresh:"Actualiser", detecting:"Détection…", allGpus:"Tous les GPU", allGpusHelp:"Laisser le mineur utiliser automatiquement tous les GPU compatibles", noGpu:"Aucun GPU détaillé détecté. Tu peux utiliser les IDs manuels ci-dessous.", manualIds:"IDs manuels / diagnostic", savedGpuIds:"GPU IDs enregistrés", source:"Source", perGpuTuning:"Réglages par GPU", perGpuHelp:"Core clock, limite de puissance et ventilateur peuvent être définis indépendamment pour chaque GPU sélectionné. Une valeur vide reste inchangée.", coreClock:"Core clock MHz", powerLimit:"Power limit W", fan:"Ventilateur %", inherit:"Défaut / inchangé", minerApiPort:"Port API mineur", disableCpu:"Désactiver CPU", gpuOverlap:"Autoriser le partage des mêmes GPU avec un autre processus (avancé / dual mining)", advancedArgs:"Arguments avancés", advancedPlaceholder:"Arguments spécifiques au mineur non couverts par MinerDesk",
  scheduler:"Planificateur", schedulerHelp:"Le scheduler fonctionne dans le backend, même si aucune fenêtre web n'est ouverte.", addWindow:"Ajouter une plage", noSchedule:"Aucune plage horaire.", scheduleName:"Plage de minage", active:"Activée", delete:"Supprimer", startTime:"Début", endTime:"Fin", profilesAffected:"Profils concernés", crossesMidnight:"Les plages qui traversent minuit sont gérées automatiquement (ex. 22:00 → 07:00).", lines:"lignes",
  afterMining:"Après le minage", doNothing:"Ne rien faire", sleepPc:"Mettre en veille", hibernatePc:"Mettre en veille prolongée", countdownSeconds:"Compte à rebours (secondes)", requirePowerConfirmation:"Exiger une fenêtre Desktop/Web ouverte pour confirmer", wakeBeforeStart:"Réveiller le PC avant le début", wakeMinutesBefore:"Réveil X minutes avant", wakeWindowsNote:"Les minuteurs de réveil sont créés automatiquement sous Windows ; le matériel et le plan d'alimentation doivent les autoriser.", sleepCountdownTitle:"Mise en veille programmée", hibernateCountdownTitle:"Veille prolongée programmée", scheduleEnded:"La plage de minage « {name} » est terminée.", closeCancelsSleep:"L'action sera exécutée à zéro. Fermer ou annuler cette fenêtre empêche la mise en veille.", sleepNow:"Mettre en veille maintenant", hibernateNow:"Hiberner maintenant", cancel:"Annuler", privilegedBackend:"Backend privilégié", backendOnline:"Backend en ligne", backendOffline:"Backend hors ligne", backendConnected:"Connecté", startBackend:"Démarrer le backend", startingBackend:"Démarrage…", restartBackend:"Redémarrer le backend", repairBackend:"Réparer le backend", backendDiagnostics:"Diagnostic du backend", taskInstalled:"tâche installée", taskMissing:"tâche absente", backendChecking:"vérification…", portUsedBy:"port utilisé par", taskState:"Tâche planifiée", lastTaskResult:"Dernier résultat", backendExecutable:"Exécutable backend", listener:"Écoute du port", backendActionFailed:"Échec de l'action backend",
  webTitle:"Interface web & headless", webHelp:"L'application desktop exécute toujours un serveur web/API local. Il peut aussi être exposé au réseau local.", currentMode:"Mode actuel",minerCrashGuard:"Protection anti-crash des mineurs",minerCrashGuardActive:"Active · Job Object Windows",minerCrashGuardUnavailable:"Indisponible / non applicable", localUrl:"URL web locale", configFile:"Configuration", webPort:"Port web", lanAccess:"Autoriser l'accès LAN", lanAccessHelp:"Écouter sur 0.0.0.0 afin que les autres appareils du réseau local puissent ouvrir MinerDesk.", accessToken:"Token d'accès distant", generateToken:"Générer un token", restartRequired:"Un changement de port ou d'écoute LAN nécessite de redémarrer MinerDesk.", lanUrl:"Exemple URL LAN", language:"Langue", languageHelp:"L'anglais est la langue par défaut. Le choix est partagé par l'interface desktop et web.", windowsSecurity:"Sécurité Windows", windowsSecurityHelp:"Les règles concernent uniquement les mineurs gérés par MinerDesk.", firewall:"Pare-feu sortant", firewallHelp:"Règles sortantes par exécutable téléchargé.", defender:"Exclusion Microsoft Defender", defenderHelp:"Exclut uniquement le dossier géré des mineurs.", enabledState:"Activé", enable:"Activer", folder:"Dossier", supportedEngines:"Moteurs supportés", supportedHelp:"Téléchargement GitHub automatique ou exécutable personnalisé.", manualPath:"Chemin manuel", saveOk:"Configuration enregistrée", commandSent:"Commande envoyée", download:"Téléchargement", gpuDetection:"Détection GPU", keepGpu:"Au moins un GPU doit rester sélectionné. Utilise « Tous les GPU » pour revenir au mode automatique.", confirmDelete:"Supprimer ce profil de mineur ?", webTokenSession:"Token web de cette session", emptyLocal:"Vide en desktop/local", tokenRemoteHint:"Les clients distants doivent utiliser ?token=... ou l'en-tête X-MinerDesk-Token.",
  devTipKicker:"SOUTIEN VOLONTAIRE",devTipTitle:"Soutenir le développement de MinerDesk",devTipHelp:"Facultatif et à 0 % par défaut. Si vous choisissez un tip, MinerDesk mine ponctuellement pour le développeur pendant ce pourcentage du temps, puis revient automatiquement à votre wallet. Modifiable ou désactivable à tout moment.",devTipPercent:"Dev tip",devTipDetected:"Réseau de paiement détecté",devTipUnsupported:"Réseau non reconnu pour le moment — le dev tip ne sera pas utilisé sur ce profil.",devTipOff:"Aucun tip — MinerDesk reste entièrement disponible.",devTipThanksSmall:"Une petite étincelle aide déjà ✦",devTipThanks:"Merci de soutenir le développement ♥",devTipThanksBig:"Un super soutien — merci ! ✨",devTipActive:"DEV TIP"};

// Core language packs. Less common technical help text intentionally falls back to English.
const es: Dict = {dashboard:"Panel",miners:"Mineros",schedules:"Horarios",console:"Consola",settings:"Ajustes",dashboardTitle:"Panel multi-minero",minersTitle:"Mineros y perfiles",schedulesTitle:"Horarios de minería",settingsTitle:"Ajustes",save:"Guardar",startAll:"Iniciar todos",stopAll:"Detener todos",start:"Iniciar",stop:"Detener",restart:"Reiniciar",activeMiners:"Mineros activos",totalPower:"Potencia total",maxTemp:"Temp. máx.",profiles:"Perfiles",add:"Añadir",name:"Nombre",engine:"Motor",algorithm:"Algoritmo",pool:"Pool",wallet:"Wallet / usuario",secondaryWallet:"Wallet secundaria",gpuTuning:"GPU y ajustes",gpuUse:"GPU a usar",refresh:"Actualizar",allGpus:"Todas las GPU",perGpuTuning:"Ajustes por GPU",coreClock:"Reloj del núcleo MHz",powerLimit:"Límite de potencia W",fan:"Ventilador %",scheduler:"Planificador",webTitle:"Interfaz web y headless",webPort:"Puerto web",lanAccess:"Permitir acceso LAN",accessToken:"Token de acceso remoto",language:"Idioma",windowsSecurity:"Seguridad de Windows",supportedEngines:"Motores compatibles"};
const pt: Dict = {dashboard:"Painel",miners:"Mineradores",schedules:"Horários",console:"Console",settings:"Configurações",dashboardTitle:"Painel multi-minerador",minersTitle:"Mineradores e perfis",schedulesTitle:"Horários de mineração",settingsTitle:"Configurações",save:"Salvar",startAll:"Iniciar todos",stopAll:"Parar todos",start:"Iniciar",stop:"Parar",restart:"Reiniciar",activeMiners:"Mineradores ativos",totalPower:"Potência total",maxTemp:"Temp. máx.",profiles:"Perfis",add:"Adicionar",name:"Nome",engine:"Motor",algorithm:"Algoritmo",pool:"Pool",wallet:"Carteira / usuário",secondaryWallet:"Carteira secundária",gpuTuning:"GPU e ajustes",gpuUse:"GPUs a usar",refresh:"Atualizar",allGpus:"Todas as GPUs",perGpuTuning:"Ajustes por GPU",coreClock:"Clock do núcleo MHz",powerLimit:"Limite de potência W",fan:"Ventoinha %",scheduler:"Agendador",webTitle:"Interface web e headless",webPort:"Porta web",lanAccess:"Permitir acesso LAN",accessToken:"Token de acesso remoto",language:"Idioma",windowsSecurity:"Segurança do Windows",supportedEngines:"Motores suportados"};
const de: Dict = {dashboard:"Dashboard",miners:"Miner",schedules:"Zeitpläne",console:"Konsole",settings:"Einstellungen",dashboardTitle:"Multi-Miner-Dashboard",minersTitle:"Miner & Profile",schedulesTitle:"Mining-Zeitpläne",settingsTitle:"Einstellungen",save:"Speichern",startAll:"Alle starten",stopAll:"Alle stoppen",start:"Start",stop:"Stopp",restart:"Neustart",activeMiners:"Aktive Miner",totalPower:"Gesamtleistung",maxTemp:"Max. Temp.",profiles:"Profile",add:"Hinzufügen",name:"Name",engine:"Miner",algorithm:"Algorithmus",pool:"Pool",wallet:"Wallet / Benutzer",secondaryWallet:"Sekundäre Wallet",gpuTuning:"GPU & Tuning",gpuUse:"Zu verwendende GPUs",refresh:"Aktualisieren",allGpus:"Alle GPUs",perGpuTuning:"Tuning pro GPU",coreClock:"Core-Takt MHz",powerLimit:"Power-Limit W",fan:"Lüfter %",scheduler:"Zeitplaner",webTitle:"Weboberfläche & Headless",webPort:"Web-Port",lanAccess:"LAN-Zugriff erlauben",accessToken:"Remote-Zugriffstoken",language:"Sprache",windowsSecurity:"Windows-Sicherheit",supportedEngines:"Unterstützte Miner"};
const zh: Dict = {dashboard:"仪表盘",miners:"矿工",schedules:"计划",console:"控制台",settings:"设置",dashboardTitle:"多矿工仪表盘",minersTitle:"矿工与配置",schedulesTitle:"挖矿计划",settingsTitle:"设置",save:"保存",startAll:"全部启动",stopAll:"全部停止",start:"启动",stop:"停止",restart:"重启",activeMiners:"活动矿工",totalPower:"总功耗",maxTemp:"最高温度",profiles:"配置",add:"添加",name:"名称",engine:"矿工程序",algorithm:"算法",pool:"矿池",wallet:"钱包 / 用户名",secondaryWallet:"第二钱包",gpuTuning:"GPU 与调优",gpuUse:"使用的 GPU",refresh:"刷新",allGpus:"所有 GPU",perGpuTuning:"按 GPU 调优",coreClock:"核心频率 MHz",powerLimit:"功耗限制 W",fan:"风扇 %",scheduler:"计划任务",webTitle:"Web 界面与无头模式",webPort:"Web 端口",lanAccess:"允许局域网访问",accessToken:"远程访问令牌",language:"语言",windowsSecurity:"Windows 安全",supportedEngines:"支持的矿工程序"};
const hi: Dict = {dashboard:"डैशबोर्ड",miners:"माइनर",schedules:"समय-सारणी",console:"कंसोल",settings:"सेटिंग्स",dashboardTitle:"मल्टी-माइनर डैशबोर्ड",minersTitle:"माइनर और प्रोफ़ाइल",schedulesTitle:"माइनिंग समय-सारणी",settingsTitle:"सेटिंग्स",save:"सहेजें",startAll:"सभी शुरू करें",stopAll:"सभी रोकें",start:"शुरू",stop:"रोकें",restart:"रीस्टार्ट",activeMiners:"सक्रिय माइनर",totalPower:"कुल पावर",maxTemp:"अधिकतम तापमान",profiles:"प्रोफ़ाइल",add:"जोड़ें",name:"नाम",engine:"इंजन",algorithm:"एल्गोरिदम",pool:"पूल",wallet:"वॉलेट / यूज़र",secondaryWallet:"दूसरा वॉलेट",gpuTuning:"GPU और ट्यूनिंग",gpuUse:"उपयोग किए जाने वाले GPU",refresh:"रीफ्रेश",allGpus:"सभी GPU",perGpuTuning:"प्रति-GPU ट्यूनिंग",coreClock:"कोर क्लॉक MHz",powerLimit:"पावर सीमा W",fan:"फैन %",scheduler:"शेड्यूलर",webTitle:"वेब इंटरफ़ेस और हेडलेस",webPort:"वेब पोर्ट",lanAccess:"LAN एक्सेस अनुमति",accessToken:"रिमोट एक्सेस टोकन",language:"भाषा",windowsSecurity:"Windows सुरक्षा",supportedEngines:"समर्थित इंजन"};

const bn: Dict = {dashboard:"ড্যাশবোর্ড",miners:"মাইনার",schedules:"সময়সূচি",console:"কনসোল",settings:"সেটিংস",dashboardTitle:"মাল্টি-মাইনার ড্যাশবোর্ড",minersTitle:"মাইনার ও প্রোফাইল",schedulesTitle:"মাইনিং সময়সূচি",settingsTitle:"সেটিংস",save:"সংরক্ষণ",startAll:"সব চালু করুন",stopAll:"সব বন্ধ করুন",start:"চালু",stop:"বন্ধ",restart:"পুনরায় চালু",activeMiners:"সক্রিয় মাইনার",totalPower:"মোট শক্তি",maxTemp:"সর্বোচ্চ তাপমাত্রা",profiles:"প্রোফাইল",add:"যোগ করুন",name:"নাম",engine:"ইঞ্জিন",algorithm:"অ্যালগরিদম",pool:"পুল",wallet:"ওয়ালেট / ব্যবহারকারী",secondaryWallet:"দ্বিতীয় ওয়ালেট",gpuTuning:"GPU ও টিউনিং",gpuUse:"ব্যবহৃত GPU",refresh:"রিফ্রেশ",allGpus:"সব GPU",perGpuTuning:"প্রতি-GPU টিউনিং",coreClock:"কোর ক্লক MHz",powerLimit:"পাওয়ার সীমা W",fan:"ফ্যান %",scheduler:"শিডিউলার",webTitle:"ওয়েব ইন্টারফেস ও হেডলেস",webPort:"ওয়েব পোর্ট",lanAccess:"LAN অ্যাক্সেস অনুমতি",accessToken:"রিমোট অ্যাক্সেস টোকেন",language:"ভাষা",windowsSecurity:"Windows নিরাপত্তা",supportedEngines:"সমর্থিত ইঞ্জিন"};
const ur: Dict = {dashboard:"ڈیش بورڈ",miners:"مائنرز",schedules:"شیڈول",console:"کنسول",settings:"ترتیبات",dashboardTitle:"ملٹی مائنر ڈیش بورڈ",minersTitle:"مائنرز اور پروفائلز",schedulesTitle:"مائننگ شیڈول",settingsTitle:"ترتیبات",save:"محفوظ کریں",startAll:"سب شروع کریں",stopAll:"سب روکیں",start:"شروع",stop:"روکیں",restart:"دوبارہ شروع",activeMiners:"فعال مائنرز",totalPower:"کل پاور",maxTemp:"زیادہ سے زیادہ درجہ حرارت",profiles:"پروفائلز",add:"شامل کریں",name:"نام",engine:"انجن",algorithm:"الگورتھم",pool:"پول",wallet:"والیٹ / صارف",secondaryWallet:"ثانوی والیٹ",gpuTuning:"GPU اور ٹیوننگ",gpuUse:"استعمال ہونے والے GPU",refresh:"ریفریش",allGpus:"تمام GPU",perGpuTuning:"فی GPU ٹیوننگ",coreClock:"کور کلاک MHz",powerLimit:"پاور حد W",fan:"فین %",scheduler:"شیڈولر",webTitle:"ویب انٹرفیس اور ہیڈلیس",webPort:"ویب پورٹ",lanAccess:"LAN رسائی کی اجازت",accessToken:"ریموٹ رسائی ٹوکن",language:"زبان",windowsSecurity:"Windows سیکیورٹی",supportedEngines:"معاون انجن"};
const id: Dict = {dashboard:"Dasbor",miners:"Penambang",schedules:"Jadwal",console:"Konsol",settings:"Pengaturan",dashboardTitle:"Dasbor multi-penambang",minersTitle:"Penambang & profil",schedulesTitle:"Jadwal penambangan",settingsTitle:"Pengaturan",save:"Simpan",startAll:"Mulai semua",stopAll:"Hentikan semua",start:"Mulai",stop:"Hentikan",restart:"Mulai ulang",activeMiners:"Penambang aktif",totalPower:"Daya total",maxTemp:"Suhu maks.",profiles:"Profil",add:"Tambah",name:"Nama",engine:"Mesin",algorithm:"Algoritma",pool:"Pool",wallet:"Dompet / pengguna",secondaryWallet:"Dompet sekunder",gpuTuning:"GPU & tuning",gpuUse:"GPU yang digunakan",refresh:"Segarkan",allGpus:"Semua GPU",perGpuTuning:"Tuning per GPU",coreClock:"Core clock MHz",powerLimit:"Batas daya W",fan:"Kipas %",scheduler:"Penjadwal",webTitle:"Antarmuka web & headless",webPort:"Port web",lanAccess:"Izinkan akses LAN",accessToken:"Token akses jarak jauh",language:"Bahasa",windowsSecurity:"Keamanan Windows",supportedEngines:"Mesin yang didukung"};
const ar: Dict = {dashboard:"لوحة التحكم",miners:"المعدّنون",schedules:"الجداول",console:"وحدة التحكم",settings:"الإعدادات",dashboardTitle:"لوحة تحكم متعددة المعدّنين",minersTitle:"المعدّنون والملفات",schedulesTitle:"جداول التعدين",settingsTitle:"الإعدادات",save:"حفظ",startAll:"تشغيل الكل",stopAll:"إيقاف الكل",start:"تشغيل",stop:"إيقاف",restart:"إعادة تشغيل",activeMiners:"المعدّنون النشطون",totalPower:"إجمالي الطاقة",maxTemp:"أقصى حرارة",profiles:"الملفات",add:"إضافة",name:"الاسم",engine:"المحرّك",algorithm:"الخوارزمية",pool:"المجمع",wallet:"المحفظة / المستخدم",secondaryWallet:"المحفظة الثانوية",gpuTuning:"GPU والضبط",gpuUse:"وحدات GPU المستخدمة",refresh:"تحديث",allGpus:"كل وحدات GPU",perGpuTuning:"ضبط لكل GPU",coreClock:"تردد النواة MHz",powerLimit:"حد الطاقة W",fan:"المروحة %",scheduler:"الجدولة",webTitle:"واجهة الويب والوضع بدون واجهة",webPort:"منفذ الويب",lanAccess:"السماح بالوصول عبر LAN",accessToken:"رمز الوصول البعيد",language:"اللغة",windowsSecurity:"أمان Windows",supportedEngines:"المحركات المدعومة"};
const ru: Dict = {dashboard:"Панель",miners:"Майнеры",schedules:"Расписание",console:"Консоль",settings:"Настройки",dashboardTitle:"Панель нескольких майнеров",minersTitle:"Майнеры и профили",schedulesTitle:"Расписание майнинга",settingsTitle:"Настройки",save:"Сохранить",startAll:"Запустить все",stopAll:"Остановить все",start:"Запуск",stop:"Стоп",restart:"Перезапуск",activeMiners:"Активные майнеры",totalPower:"Общая мощность",maxTemp:"Макс. температура",profiles:"Профили",add:"Добавить",name:"Имя",engine:"Движок",algorithm:"Алгоритм",pool:"Пул",wallet:"Кошелек / пользователь",secondaryWallet:"Второй кошелек",gpuTuning:"GPU и настройка",gpuUse:"Используемые GPU",refresh:"Обновить",allGpus:"Все GPU",perGpuTuning:"Настройка по GPU",coreClock:"Частота ядра MHz",powerLimit:"Лимит мощности W",fan:"Вентилятор %",scheduler:"Планировщик",webTitle:"Веб-интерфейс и headless",webPort:"Веб-порт",lanAccess:"Разрешить доступ LAN",accessToken:"Токен удаленного доступа",language:"Язык",windowsSecurity:"Безопасность Windows",supportedEngines:"Поддерживаемые майнеры"};
const ja: Dict = {dashboard:"ダッシュボード",miners:"マイナー",schedules:"スケジュール",console:"コンソール",settings:"設定",dashboardTitle:"マルチマイナーダッシュボード",minersTitle:"マイナーとプロファイル",schedulesTitle:"マイニングスケジュール",settingsTitle:"設定",save:"保存",startAll:"すべて開始",stopAll:"すべて停止",start:"開始",stop:"停止",restart:"再起動",activeMiners:"稼働中マイナー",totalPower:"総消費電力",maxTemp:"最高温度",profiles:"プロファイル",add:"追加",name:"名前",engine:"エンジン",algorithm:"アルゴリズム",pool:"プール",wallet:"ウォレット / ユーザー",secondaryWallet:"セカンダリウォレット",gpuTuning:"GPU とチューニング",gpuUse:"使用する GPU",refresh:"更新",allGpus:"すべての GPU",perGpuTuning:"GPU ごとの設定",coreClock:"コアクロック MHz",powerLimit:"電力制限 W",fan:"ファン %",scheduler:"スケジューラ",webTitle:"Web インターフェースとヘッドレス",webPort:"Web ポート",lanAccess:"LAN アクセスを許可",accessToken:"リモートアクセストークン",language:"言語",windowsSecurity:"Windows セキュリティ",supportedEngines:"対応エンジン"};

const packs: Record<string, Dict> = { en, fr, es, pt, de, zh, hi, bn, ur, id, ar, ru, ja };

export function tr(language: string, key: string): string {
  return packs[language]?.[key] ?? en[key] ?? key;
}

export function languageDirection(language: string): "ltr" | "rtl" {
  return language === "ar" || language === "ur" ? "rtl" : "ltr";
}

export function dayNames(language: string): string[] {
  const locale: Record<string,string> = {en:"en-US",fr:"fr-FR",es:"es-ES",pt:"pt-BR",de:"de-DE",zh:"zh-CN",hi:"hi-IN",bn:"bn-BD",ur:"ur-PK",id:"id-ID",ar:"ar",ru:"ru-RU",ja:"ja-JP"};
  const fmt = new Intl.DateTimeFormat(locale[language] || "en-US", { weekday: "short" });
  const monday = new Date(Date.UTC(2026, 0, 5));
  return Array.from({length:7}, (_,i) => fmt.format(new Date(monday.getTime()+i*86400000)));
}
